### ISSUE TITLE
Open license?

### ISSUE THREAD

**Issue by schwehr** [KhaosResearch/RESEO#1]
Is it possible to assign a license to this repository (e.g. by adding a LICENSE file)?  Without that, I can't take a look at it.

Best would be to use one of the SPDX listed licenses that is truly open.

e.g. https://spdx.org/licenses/CC-BY-4.0.html or https://spdx.org/licenses/CC0-1.0.html

Thanks!

**Comment by jfaldanam** [comment]
Hey! I have uploaded the [License (MIT)](https://github.com/KhaosResearch/RESEO/commit/2d4df90a862f3ca8aae9b04b95f3f0c82a4e48bb), thank you for letting us know it was missing!

Additionally, if you are interested in the ontology, we are going to publish in the following days a new version making it more compliant with the FAIR principles in [KhaosResearch/REmoteSEnsingOntology](https://github.com/KhaosResearch/REmoteSEnsingOntology), and this respository will be archived with the original version linked in the article.
